@startuml Match
left to right direction

skinparam actorStyle awesome
"Utilisateur\n(Arbitre)" as User
package App {
    usecase "Définir les joueurs" as (InitGame)
    usecase "Démarrer le match" as (StartGame)
    usecase "Démarrer un set" as (StartSet)
    usecase "Ajouter 1 point" as (AddPoint)
}

:User: --> (InitGame)
:User: --> (StartGame)
:User: --> (StartSet)
:User: --> (AddPoint)
@enduml
